### ISSUE TITLE
Make Facebook app

### ISSUE THREAD

**Issue by mikaeilorfanian** [szn/uprzejmiedonosze-backend#11]
Follow instructions here(partially pasted below): http://python-social-auth.readthedocs.io/en/latest/backends/facebook.html
Facebook uses OAuth2 for its auth process. Further documentation at Facebook development resources.
Register a new application at Facebook App Creation, don’t use localhost as App Domains and Site URL since Facebook won’t allow them. Use a placeholder like myapp.com and define that domain in your /etc/hosts or similar file.

**Comment by szn** [comment]
Will do.

**Comment by szn** [comment]
I bet you will need a Google+ something as well.

**Comment by mikaeilorfanian** [comment]
yes, follow these instructions: http://python-social-auth.readthedocs.io/en/latest/backends/google.html#google-sign-in

**Comment by szn** [comment]
Done (details on Slack's #backend channel)
